# Generated by Django 5.1.1 on 2024-10-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок объявления')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='advert_images/', verbose_name='Основное изображение')),
                ('full_url', models.URLField(max_length=500, verbose_name='Ссылка на полное объявление')),
            ],
        ),
    ]
